. ~/.config/fish/aliases.fish

#set -gx TERM screen-256color

set -gx EDITOR nvim
set -gx VISUAL nvim

# add direnv support (https://direnv.net/)
#echo 'eval (direnv hook fish)'

set theme_color_scheme gruvbox

if status is-login
    . ~/.config/fish/env.fish
end

function fish_greeting

	# Greeting messages
	set powered_msgs \
		"candy!" \
		"rubber bands" \
		"a black hole" \
		"logic" \
		"electromagnetic cheese"

	# Randomly pick a message
	set chosen_msg (random)"%"(count $powered_msgs)
	set chosen_msg $powered_msgs[(math $chosen_msg"+1")]

	# Output it to the console
	printf (set_color F90)"Welcome! This terminal session is powered by %s\n" $chosen_msg

end

function pass-gen
    command cat /dev/urandom | env LC_ALL=C tr -dc 'A-Za-z0-9_!@#$%^&*()[\-+];.:{|}~<=>?' | head -c 24 && echo
end

function history
    builtin history --show-time='%F '
end

# QRencode
function qr
    qrencode $argv -t ANSIUTF8 -o -;
end

# switch to namespace in k8s
#function kcd
#    kubectl config set-context $(kubectl config current-context) --namespace $argv
#end

# cek port listen
function listen-port
    sudo lsof -n -i4TCP:$argv | grep LISTEN
end

# check web headers using wget
function cek-headers
  clear && wget -q -S -O - $argv > /dev/null
end

starship init fish | source

### GENERATED BY ROBBYRUSSELL
#. /usr/local/lib/node_modules/robbyrussell/adapters/adapter.fish
### GENERATED BY ROBBYRUSSELL
